title:            May Wang's Homepage
description:      Shanghai Jiao Tong University
disqus_shortname: 
reading_time:     false
comments:         yes
words_per_minute: 
favicon:          avatar.jpg
# Your site's domain goes here (eg: //MayWang-SJTU.github.io, etc)
# When testing locally leave blank or use http://localhost:4000
url:
baseurl:          
rss_url:          

# Owner/author information
owner:
  name:           May Wang
  title:          SJTU
  address:        Shanghai, China
  avatar:         avatar.jpg
  bio:            "Some Observations On TECH and LIFE."
  email:          wangmei1994515@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        MayChandle
  facebook:       MayWang515
  github:         MayWang-SJTU
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:    
  
  workHistory:
    - work1:
      company: Indoor Localization
      location: Shanghai Jiao Tong University
      title: Intelligent Internet of Things Lab (IIoT)
      started: 2015
      duration: (2015.3 - Present)
      description: Last semester I mainly focus on studying the temporal correlation effects on RSS finger printing based indoor localization method. From my theoretical derivation and scientific calculation for now, I have found that temporal correlation of signals can definitely correct the localization criteria for MLE method, so that it can significantly improve the fundamental limits like accuracy and reliability. With expected experiment results, I have wrote a paper as the first author and submitted it for INFOCOM this summer.
    - work2:
      company: Cellular Network
      location: Shanghai Jiao Tong University
      title: Institute of Wireless Communication and Technology (IWCT) and Ericsson
      started: 2014
      duration: (2014.7 - 2015.4)
      description: During the second half of last year, I assisted in the completion of a cooperation project between IWCT (Institute of Wireless Communication and Technology) and Ericsson. I wrote a simulation software with C++ to model the user behavior propagation in 3GPP communication network. In addition, this project gave me an idea on future research areas on NFV network optimization.
    - work3:
      company: Intelligent Transportation
      location: Shanghai Jiao Tong University
      title: Intelligent Internet of Things Lab (IIoT)
      started: 2014
      duration: (2014.9 - 2015.1)
      description: Last year I participated in a research on intelligent transportation. We designed a system to make lane-level localization with accelerator, gyroscope and GPS on smartphone.
  
  educationHistory:
    - education1:
      organization: Shanghai Jiao Tong University
      degree: Bachelor
      major: Electric Engineering & Computer Science
      started: 2012
      duration: (2012 - 2016)
      description: I am a student of IEEE pilot class in SJTU, and I will get my bachelor's degree with a double major EE&CS. I wish to say that I am really interested in further study in US, as I have more than one year`s experience in Wireless lab of our college, and I have strong research interests on wireless network and communication.
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: iBT-101
  programmingSkills:
    - skill1:
      name: C++
      percentage: 90%
    - skill2:
      name: Python
      percentage: 90%
    - skill3:
      name: Java
      percentage: 60%
    - skill4:
      name: Matlab/Mathematica
      percentage: 80%
    - skill5:
      name: Android/iOS
      percentage: 70%

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    China/Beijing
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 1

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
